### ISSUE TITLE
Unresolved reference to FarseerPhysics in editor project

### ISSUE THREAD

**Issue by markgarcia** [raycrasher/Fell-Sky#3]
As far as I can see it does not point to a specific NuGet package, though I could definitely try using one.

**Comment by raycrasher** [comment]
FarseerPhysics MonoGame.dll (in the Dependencies folder) must be referenced and included in the executable path. I don't know why this happens though.

**Comment by raycrasher** [comment]
Ahh I found it - Remove FarseerPhysics.dll from the References, and then add FarseerPhysics MonoGame.dll in the Dependencies folder.
